[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
fractionalize_cnft = "J8tMVQ4K8LNth8XvJoQ9g5jPJinebH1MnQvcbrAGHozP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -r ts-node/register -t 100000 tests/**/*.ts"


